FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Andela Book A Meal

Book a meal is a web development challenge by Andela which allows caterer(s)
to post menus of available meals and customers to book meals on the same
platform. This is the RESTful API documentation for this project.

Note that this API **expects** the data posted to it to be in JSON format. 
Therefore the following header has to be included:
```
Content-Type: application/json
```
Also, for any of the protected endpoints the following header must be 
included:
```
Authorization: Bearer + <token>
```
The `<token>` in this case is the `access_token` that will be received
after the user has been successfully authenticated.

# Group Authentication

## Sign Up [/auth/signup]

### Create Account[POST]

Create a new user account. The new account will have the role of a
customer until made a caterer by the default administrator.

+ Request (application/json)

        {
            "username": "John Doe",
            "email": "john@doe.com",
            "password": "jane-doe"
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "username": "John Doe",
            "email": "john@doe.com"
        }

## Login [/auth/login]

### Sign In [POST]

A user can sign in with their email and password. After signing in, the
user is redirected to their home page depending on their role. This is 
either as a CATERER or as a CUSTOMER.

Authentication has been implemented using JWT and therefore for any 
previleged routes, the `Authorization: Bearer + token` header is 
required.

+ Request (application/json)

        {
            "email": "john@doe.com",
            "password": "jane-doe"
        }

+ Response 200 (application/json)

        {
            "access_token": "<token-here>"
        }